routes/web.php
    Route::post('division/divisionSelectAjaxList', 'DivisionController@divisionSelectAjaxList')->name('division.divisionSelectAjaxList');    // Ajax Division List
    Route::get('division/{id}', 'DivisionController@edit')->name('division.edit');   // edit
    Route::post('division/{id}', 'DivisionController@update')->name('division.update');    // update
    Route::delete('division/{id}', 'DivisionController@destroy')->name('division.delete');    // delete

    //*  District Route Section */
    Route::get('district/list', 'DistrictController@list')->name('district.list');   // index
    Route::get('district/add', 'DistrictController@form')->name('district.form');    // create
    Route::post('district/store', 'DistrictController@store')->name('district.store');   // store
    Route::post('district/districtSelectAjaxList', 'DistrictController@districtSelectAjaxList')->name('district.districtSelectAjaxList');    // Ajax District List
    Route::get('district/{id}', 'DistrictController@edit')->name('district.edit');   // edit
    Route::post('district/{id}', 'DistrictController@update')->name('district.update');    // update
    Route::delete('district/{id}', 'DistrictController@destroy')->name('district.delete');    // delete

    //*  Upazila-- Route Section */
    Route::get('upazila/list', 'UpazilaController@list')->name('upazila.list');   // index
    Route::get('upazila/add', 'UpazilaController@form')->name('upazila.form');    // create
    Route::post('upazila/store', 'UpazilaController@store')->name('upazila.store');   // store
    Route::post('upazila/upazilaSelectAjaxList', 'UpazilaController@upazilaSelectAjaxList')->name('upazila.upazilaSelectAjaxList');    // Ajax Upazila List
    Route::get('upazila/{id}', 'UpazilaController@edit')->name('upazila.edit');   // edit
    Route::post('upazila/{id}', 'UpazilaController@update')->name('upazila.update');    // update
    Route::delete('upazila/{id}', 'UpazilaController@destroy')->name('upazila.delete');    // delete

    //*  Union Route Section */
    Route::get('union/list', 'UnionController@list')->name('union.list');   // index
    Route::get('union/add', 'UnionController@form')->name('union.form');    // create
    Route::post('union/store', 'UnionController@Store')->name('union.store');   // store
    Route::post('union/unionSelectAjaxList', 'UnionController@unionSelectAjaxList')->name('union.unionSelectAjaxList');    // Ajax District List
    Route::get('union/{id}', 'UnionController@edit')->name('union.edit');   // edit
    Route::post('union/{id}', 'UnionController@update')->name('union.update');    // update
    Route::delete('union/{id}', 'UnionController@destroy')->name('union.delete');    // delete

    Route::get('/home', 'HomeController@index')->name('dashboard');

    /**********  Office Budget Project Routes    **********/

//    Institute Routes
    Route::Resource('/institutes', 'InstituteController');

//    Budget Code Routes
    Route::Resource('/budget-code', 'BudgetCodeController');
    Route::post('/budget-code/get-code-list', 'BudgetCodeController@getBudgetCodeList')->name('budget-code.getBudgetCodeList');
    Route::post('/budget-code/get-code-by-id', 'BudgetCodeController@getBudgetCodeById')->name('budget-code.getBudgetCodeById');

//    Budget Type Routes
    Route::Resource('/budget-type', 'BudgetTypeController');

//    Budget Sub Type Routes
    Route::post('/budget-sub-type/get-ajax-list', 'BudgetSubTypeController@ajaxBgtSubTypList')->name('budget-sub-type.ajaxBgtSubTypList');
    Route::post('/budget-sub-type/get-ajax-code', 'BudgetSubTypeController@ajaxBgtSubTypCode')->name('budget-sub-type.ajaxBgtSubTypCode');
    Route::Resource('/budget-sub-type', 'BudgetSubTypeController');

//    Items Routes
    Route::Resource('/items', 'ItemController');

//    Official Budget Routes
//    Office Budget
    Route::post('/office-budget/get-budget-code', 'OfficeBudgetController@getBudgetCodeByType')->name('office-budge.getBudgetCodeByType');
    Route::post('/office-budget/budget-approve', 'OfficeBudgetController@budgetApproveReject')->name('office-budge.budgetApproveReject');
    Route::Resource('/office-budget', "OfficeBudgetController");

//    Office Budget Expense
    Route::post('/office-budget-expense/budget-expense-approve', 'OfficeBudgetController@budgetExpenseApproveReject')->name('office-budge.budgetExpenseApproveReject');
    Route::post('/office-budget-expense/expense-data-ajax', 'OfficeBudgetExpenseController@expenseDataAjax')->name('office-budget-expense.expenseDataAjax');
    Route::post('/office-budget-expense/budget-approve', 'OfficeBudgetExpenseController@budgetExpenseApproveReject')->name('office-budget-expense.budgetExpenseApproveReject');
    Route::Resource('/office-budget-expense', "OfficeBudgetExpenseController");

//    Office Budget Balance
    Route::Resource('/office-balance', "OfficeBalanceController");

    //    All Ajax Helper Controller
    Route::post('/ajax-helper/unit-list', 'AllAjaxHelperController@getUnitList')->name('ajax-helper.getUnitList');
    Route::post('/ajax-helper/item-list', 'AllAjaxHelperController@getItemList')->name('ajax-helper.getItemList');

    //    Office Voucher
    Route::post('/office-voucher/voucher-approve', 'OfficeVoucherController@budgetVoucherApproveReject')->name('office-voucher.budgetVoucherApproveReject');
    Route::Resource('/office-voucher', "OfficeVoucherController");

    //    Internal Voucher
    Route::post('/internal-voucher/voucher-approve', 'InternalVoucherController@budgetVoucherApproveReject')->name('internal-voucher.budgetVoucherApproveReject');
    Route::Resource('/internal-voucher', "InternalVoucherController");

//    Internal Budget Routes
    Route::Resource('/internal-budget', "InternalBudgetController");
    Route::post('/internal-budget/budget-approve', 'InternalBudgetController@budgetExpenseApproveReject')->name('internal-budget.budgetExpenseApproveReject');
    Route::post('/internal-budget/budget-approve', 'InternalBudgetController@internalBudgetApproveReject')->name('internal-budget.internalBudgetApproveReject');

//    Internal Budget Expense
    Route::Resource('/internal-budget-expense', "InternalBudgetExpenseController");
    Route::post('/internal-budget-expense/budget-approve', 'InternalBudgetExpenseController@internalBudgetExpenseApproveReject')->name('internal-budget-expense.internalBudgetExpenseApproveReject');

//    Internal Budget Balance
    Route::Resource('/internal-balance', "InternalBalanceController");


//    Land Route
    Route::post('/lands/getLandInfoById', 'LandController@getLandInfoById')->name('lands.getLandInfoById');
    Route::resource('/lands', 'LandController');

//    Applicant Route
    Route::resource('/applicants', 'ApplicantController');

//    Land Assign Route
    Route::resource('/assign_lands', 'AssignLandController');

//    Role Routs
    Route::Resource('/roles', 'RoleController');
    Route::get('/role-setting', 'RoleController@roleSetting')->name('roles.roleSetting');
    Route::post('/role-setting', 'RoleController@roleSetting')->name('roles.roleSetting');
    Route::post('/update-role-setting', 'RoleController@updateRoleSetting')->name('roles.updateRoleSetting');

//    Permission Routs
    Route::resource('/permissions', 'PermissionController');

//    User Route
//    Route::get("/users/datatable", 'UserController@datatable')->name("users.datatable"); // for Data Table Export
//    Route::get("/users/datatable/getData", 'UserController@getData')->name("users.getData"); // for datatable Export
    Route::get("/users/export", 'UserController@export')->name("users.export"); // for datatable Export
    Route::Resource('/users', 'UserController');
    Route::get("/change-password", 'UserController@changepass')->name("users.changepass"); // for pass change
    Route::post("/change-password", 'UserController@changepass')->name("users.changepass"); // for pass change
    Route::post("/reset-password", 'UserController@resetpass')->name("users.resetpass"); // for pass reset

//    Flat Routes
    Route::get("/flats/export", 'FlatController@export')->name("flats.export"); // for datatable Export
    Route::get('/flats/assign-tenant/{flat_id?}/{tenant_id?}', 'FlatController@assignTenant')->name('flats.assignTenant'); // for Assign a Tenant to a Flat
    Route::get('/flats/unassign-tenant/{flat_id?}', 'FlatController@unAssignTenant')->name('flats.unAssignTenant'); // for Unassign a Tenant to a Flat
    Route::get('/assigned-flat-lists/{tenant_id?}', 'FlatController@assignedFlatLists')->name('flats.assignedFlatLists'); // for Assigned Flat List
    Route::Resource('/flats', 'FlatController');
    Route::post('/flats/assign-tenant', 'FlatController@saveAssignTenant')->name('flats.saveAssignTenant'); // for Save Assign Tenant to a Flat
    Route::post("/remove-flat-image", 'FlatController@removeFlatImage')->name("flats.removeFlatImage"); // for Flat Image Ajax Remove

//    Tenant Routes
    Route::get("/tenants/export", 'TenantController@export')->name("tenants.export"); // for datatable Export
    Route::Resource('/tenants', 'TenantController');
    Route::post("/remove-tenant-image", 'TenantController@removeTenantImage')->name("tenants.removeTenantImage"); // for Tenant Image Ajax Remove

//    Bill Router
    Route::Resource('/bills', 'BillController');
    Route::post("/ajax-get-flat-bill-data", 'BillController@ajaxGetFlatBillData')->name("bills.ajaxGetFlatBillData"); // for Get Flat Bill Data Ajax
    Route::post("/ajax-check-duplicate-bill-month", 'BillController@ajaxCheckDuplicateBillMonth')->name("bills.ajaxCheckDuplicateBillMonth"); // for Check Duplicate Bill Month Ajax
    Route::post("/ajax_get_unpaid_bill_details", 'BillController@ajaxGetUnpaidBillDetails')->name("bills.ajaxGetUnpaidBillDetails"); // for Get Unpaid Bill Data Ajax
    Route::get("/download_pdf", 'BillController@downloadPDF')->name("bills.downloadPDF"); // for Get Unpaid Bill Data Ajax

//    Payment Router

resources/views/budget_type/create.blade.php
@extends('layouts.app')

@section('pagetitle')
    <h1 class="m-0">{{ $page_title }}</h1>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Starter Page</li>
    </ol>
@endsection

@section('content')
    <form class="form-horizontal" role="form" action="{{ route('budget-type.store') }}" method="POST"
          enctype="multipart/form-data" id="reg_form">
        {{ csrf_field() }}

        {{-- Institute --}}
        <div class="card  card-info">
            <div class="card-header">
                <h3 class="card-title">বাজেটের ধরন</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    {{--                <button type="button" class="btn btn-tool" data-card-widget="remove">--}}
                    {{--                    <i class="fas fa-times"></i>--}}
                    {{--                </button>--}}
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>বাজেট ধরন <span class="reqrd"> *</span> </label>
                            <input type="text" id="budget_type_name" name="budget_type_name" class="form-control"
                                   placeholder="বাজেট ধরন" required>
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('budget_type_name'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('budget_type_name') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                        <div class="form-group">
                            <label>স্ট্যাটাস <span class="reqrd"> *</span></label>
                            <?php $status = config('constants.status.arr'); ?>
                            <select class="form-control select2bs4" id="budget_type_status" name="budget_type_status" required>
                                <option value="">--- বাছাই করুণ ---</option>
                                <?php
                                foreach ($status as $id => $val){ ?>
                                <option value="{{ $id }}">{{ $val }}</option>
                                <?php }
                                ?>
                            </select>
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('budget_type_status'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('budget_type_status') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>ধরন কোড <span class="reqrd"> *</span> </label>
                            <input type="number" id="budget_type_code" name="budget_type_code" class="form-control"
                                   placeholder="ধরন কোড" >
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('budget_type_code'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('budget_type_code') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                        <div class="form-group">
                            <label>ব্যবহারের ক্ষেত্র <span class="reqrd"> *</span></label>
                            <?php $budget_type = config('constants.budget_type.arr'); ?>
                            <select class="form-control select2bs4" id="budget_type" name="budget_type" required>
                                <option value="">--- বাছাই করুণ ---</option>
                                <?php
                                foreach ($budget_type as $id => $val){ ?>
                                <option value="{{ $id }}">{{ $val }}</option>
                                <?php }
                                ?>
                            </select>
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('budget_type'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('budget_type') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.card-body -->
        </div>

        {{--        Submit Form--}}
        <div class="card  card-primary">
            <div class="card-footer">
                <button type="submit" class="btn btn-info">Submit</button>
            </div>
        </div>

    </form>
@endsection

@section('custom_script')
    <script type="text/javascript">

        $(document).ready(function () {
            //Initialize Select2 Elements
            $('.select2').select2();

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            });

            //Datemask dd/mm/yyyy
            $('#datemask').inputmask('mm/dd/yyyy', {'placeholder': 'mm/dd/yyyy'})
            //Money Euro
            $('[data-mask]').inputmask()

        });

    </script>
@endsection

resources/views/budget_type/edit.blade.php
@extends('layouts.app')

@section('pagetitle')
    <h1 class="m-0">{{ $page_title }}</h1>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Starter Page</li>
    </ol>
@endsection

@section('content')
    <form class="form-horizontal" role="form" action="{{ route('budget-type.update', $id) }}" method="POST"
          enctype="multipart/form-data" id="reg_form">
        <input type="hidden" name="_method" value="PUT">
        {{ csrf_field() }}

        {{-- Institute --}}
        <div class="card  card-info">
            <div class="card-header">
                <h3 class="card-title">বাজেটের ধরন</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    {{--                <button type="button" class="btn btn-tool" data-card-widget="remove">--}}
                    {{--                    <i class="fas fa-times"></i>--}}
                    {{--                </button>--}}
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>বাজেট ধরন <span class="reqrd"> *</span> </label>
                            <input type="text" id="budget_type_name" name="budget_type_name" class="form-control"
                                   placeholder="বাজেট ধরন" required value="{{ $bgtTypData->budget_type_name }}">
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('budget_type_name'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('budget_type_name') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                        <div class="form-group">
                            <label>ধরন কোড </label>
                            <input type="number" id="budget_type_code" name="budget_type_code" class="form-control"
                                   placeholder="ধরন কোড" value="{{ $bgtTypData->budget_type_code }}">
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('budget_type_code'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('budget_type_code') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <!-- /.col -->

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>স্ট্যাটাস <span class="reqrd"> *</span></label>
                            <?php $status = config('constants.status.arr'); ?>
                            <select class="form-control select2bs4" id="budget_type_status" name="budget_type_status"
                                    required>
                                <option value="">--- বাছাই করুণ ---</option>
                                <?php
                                foreach ($status as $id => $val){ ?>
                                <option
                                    value="{{ $id }}" {{ $id == $bgtTypData->budget_type_status ? 'selected="selected"' : '' }}>{{ $val }}</option>
                                <?php }
                                ?>
                            </select>
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('budget_type_status'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('budget_type_status') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                        <div class="form-group">
                            <label>ব্যবহারের ক্ষেত্র <span class="reqrd"> *</span></label>
                            <?php $budget_type = config('constants.budget_type.arr'); ?>
                            <select class="form-control select2bs4" id="budget_type" name="budget_type" required>
                                <option value="">--- বাছাই করুণ ---</option>
                                <?php
                                foreach ($budget_type as $id => $val){ ?>
                                <option
                                    value="{{ $id }}" {{ $id == $bgtTypData->budget_type ? 'selected="selected"' : '' }}>{{ $val }}</option>
                                <?php }
                                ?>
                            </select>
                            <span class="help-inline col-xs-12 col-sm-7">
                            @if ($errors->has('budget_type'))
                                    <span class="help-block middle">
                                    <strong>{{ $errors->first('budget_type') }}</strong>
                                </span>
                                @endif
                        </span>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.card-body -->
        </div>

        {{--        Submit Form--}}
        <div class="card  card-primary">
            <div class="card-footer">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>

    </form>
@endsection

@section('custom_script')
    <script type="text/javascript">

        $(document).ready(function () {
            //Initialize Select2 Elements
            $('.select2').select2();

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            });

            //Datemask dd/mm/yyyy
            $('#datemask').inputmask('mm/dd/yyyy', {'placeholder': 'mm/dd/yyyy'})
            //Money Euro
            $('[data-mask]').inputmask()

        });

    </script>
@endsection

resources/views/budget_type/index.blade.php
@extends('layouts.app')

@section('pagetitle')
    <h1 class="m-0">{{ $page_title }}</h1>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Starter Page</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    @can('create-budget-type')
                        <h3 class="card-title">
                            <div class="pad_space">
                                <a href="{{ route('budget-type.create') }}" class="btn btn-block btn-secondary btn-md"
                                   title="Add">
                                    <i class="far fa-plus-square fa-lg"></i>
                                </a>
                            </div>
                        </h3>
                    @endcan
                    @can('export-flat-list')
{{--                        <h3 class="card-title">--}}
{{--                            <div class="pad_space">--}}
{{--                                <a href="{{ route('institutes.export') }}" class="btn btn-block btn-success btn-md"--}}
{{--                                   id="export_list" title="Download List">--}}
{{--                                    <i class="fas fa-file-download fa-lg"></i>--}}
{{--                                </a>--}}
{{--                            </div>--}}
{{--                        </h3>--}}
                    @endcan
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered data-table">
                        {{--                    <table id="example1" class="table table-bordered table-striped">--}}
                        <thead>
                        <tr>
                            <th>ক্রমিক নং</th>
                            <th> বাজেট ধরন </th>
                            <th> ব্যবহারের ক্ষেত্র </th>
                            <th> কোড </th>
                            <th> স্ট্যাটাস</th>
                            <th> ব্যবস্থা</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('custom_script')
    <script type="text/javascript">
        // $(function () {
        //     $(".data-table").DataTable({
        //         "responsive": true, "lengthChange": false, "autoWidth": false,
        //         "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        //     }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        // });
        $(document).ready(function () {
            // $(".data-table").DataTable({
            //     "responsive": true, "lengthChange": false, "autoWidth": false,
            //     "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            // }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');

            var table = $('.data-table').DataTable({
                lengthMenu: [[25, 50, 75, 100, -1], [25, 50, 75, 100, "All"]],
                processing: true,
                serverSide: true,
                responsive: true,
                buttons: ["copy", "csv", "excel", "pdf", "print", "colvis"],
                ajax: "{{ route('budget-type.index') }}",
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                    {data: 'budget_type_name', name: 'budget_type_name'},
                    {data: 'budget_type', name: 'budget_type'},
                    {data: 'budget_type_code', name: 'budget_type_code'},
                    {data: 'budget_type_status', name: 'budget_type_status'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');

            $(document).on("click", "a.delete-budget-type", function (ev) {
                ev.preventDefault();
                let url = $(this).attr("href");
                let id = $(this).attr("id");
                if (confirm("Do you wat to delete?")) {
                    $.ajax({
                        type: 'DELETE',
                        url: url,
                        dataType: 'json',
                        headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                        data: {id: id, "_token": "{{ csrf_token() }}"},

                        success: function (data) {
                            if (data.status == 'success') {
                                window.location.reload();
                            } else if (data.status == 'error') {
                            }
//                    data.request->session()->flash('status', 'Task was successful!');
//                    setInterval(function() {
//                    }, 5900);
                        },
                        error: function (data) {
                        }
                    });

                } else {
                    return false;
                }
            });
        });
    </script>
@endsection